"""London Gatwick Airport (LGW) destinations — May 2026."""

DESTINATIONS = {
    "LGW": {
        "name": "London Gatwick",
        "routes": {
            # UK & Ireland
            "BFS": "Belfast",
            "DUB": "Dublin",
            "EDI": "Edinburgh",
            "GCI": "Guernsey",
            "GIB": "Gibraltar",
            "GLA": "Glasgow",
            "INV": "Inverness",
            "IOM": "Isle of Man",
            "JER": "Jersey",
            "MAN": "Manchester",
            "NOC": "Knock",
            "ORK": "Cork",
            "SNN": "Shannon",
            # Spain (Mainland)
            "AGP": "Malaga",
            "ALC": "Alicante",
            "BCN": "Barcelona",
            "BIO": "Bilbao",
            "GRO": "Girona",
            "GRX": "Granada",
            "LEI": "Almeria",
            "MAD": "Madrid",
            "OVD": "Asturias",
            "REU": "Reus",
            "RMU": "Murcia",
            "SDR": "Santander",
            "SVQ": "Seville",
            "VLC": "Valencia",
            "ZAZ": "Zaragoza",
            # Balearic Islands
            "IBZ": "Ibiza",
            "MAH": "Menorca",
            "PMI": "Palma de Majorca",
            # Canary Islands
            "ACE": "Lanzarote",
            "FUE": "Fuerteventura",
            "LPA": "Gran Canaria",
            "TFS": "Tenerife South",
            # Italy
            "AOI": "Ancona",
            "BDS": "Brindisi",
            "BGY": "Milan Bergamo",
            "BLQ": "Bologna",
            "BRI": "Bari",
            "CAG": "Cagliari",
            "CTA": "Catania",
            "FCO": "Rome Fiumicino",
            "FLR": "Florence",
            "GOA": "Genoa",
            "LIN": "Milan Linate",
            "LMP": "Lampedusa",
            "MXP": "Milan Malpensa",
            "NAP": "Naples",
            "OLB": "Olbia",
            "PEG": "Perugia",
            "PMF": "Parma",
            "PMO": "Palermo",
            "PNL": "Pantelleria",
            "PSA": "Pisa",
            "TRN": "Turin",
            "TRS": "Trieste",
            "VCE": "Venice Marco Polo",
            "VRN": "Verona",
            # France
            "BIQ": "Biarritz",
            "BOD": "Bordeaux",
            "CDG": "Paris Charles de Gaulle",
            "CMF": "Chambery",
            "GNB": "Grenoble",
            "LRH": "La Rochelle",
            "LYS": "Lyon",
            "MPL": "Montpellier",
            "MRS": "Marseille",
            "NCE": "Nice",
            "NTE": "Nantes",
            "RNS": "Rennes",
            "SXB": "Strasbourg",
            "TLS": "Toulouse",
            # Corsica
            "AJA": "Ajaccio",
            "BIA": "Bastia",
            "FSC": "Figari",
            # Germany
            "BER": "Berlin",
            "CGN": "Cologne Bonn",
            "DUS": "Dusseldorf",
            "FRA": "Frankfurt",
            "HAM": "Hamburg",
            "MUC": "Munich",
            "STR": "Stuttgart",
            # Greece
            "AOK": "Karpathos",
            "ATH": "Athens",
            "CFU": "Corfu",
            "CHQ": "Chania",
            "EFL": "Kefalonia",
            "HER": "Heraklion (Crete)",
            "JMK": "Mykonos",
            "JTR": "Santorini",
            "JSI": "Skiathos",
            "KGS": "Kos",
            "KLX": "Kalamata",
            "LXS": "Lemnos",
            "MJT": "Lesbos / Mytilene",
            "PVK": "Preveza",
            "RHO": "Rhodes",
            "SKG": "Thessaloniki",
            "SMI": "Samos",
            "VOL": "Volos",
            "ZTH": "Zakynthos (Zante)",
            # Portugal & Azores
            "FAO": "Faro",
            "FNC": "Funchal (Madeira)",
            "LIS": "Lisbon",
            "OPO": "Porto",
            "PDL": "Ponta Delgada (Azores)",
            "TER": "Terceira (Azores)",
            # Turkey
            "ADB": "Izmir",
            "ASR": "Kayseri",
            "AYT": "Antalya",
            "BJV": "Bodrum",
            "DLM": "Dalaman",
            "ESB": "Ankara",
            "IST": "Istanbul",
            "TZX": "Trabzon",
            "YEI": "Bursa",
            # Poland
            "GDN": "Gdansk",
            "KRK": "Krakow",
            # Romania
            "OTP": "Bucharest",
            # Austria & Switzerland
            "BSL": "Basel",
            "GVA": "Geneva",
            "INN": "Innsbruck",
            "SZG": "Salzburg",
            "VIE": "Vienna",
            "ZRH": "Zurich",
            # Eastern Europe & Balkans
            "BUD": "Budapest",
            "DBV": "Dubrovnik",
            "LJU": "Ljubljana",
            "PRG": "Prague",
            "PUY": "Pula",
            "RIX": "Riga",
            "SJJ": "Sarajevo",
            "SOF": "Sofia",
            "SPU": "Split",
            "TGD": "Podgorica",
            "TIA": "Tirana",
            "TIV": "Tivat",
            "TLL": "Tallinn",
            "ZAD": "Zadar",
            # Scandinavia & Nordics
            "ARN": "Stockholm",
            "BGO": "Bergen",
            "BLL": "Billund",
            "CPH": "Copenhagen",
            "IVL": "Ivalo",
            "KEF": "Reykjavik",
            "KTT": "Kittila",
            "OSD": "Ostersund",
            "OSL": "Oslo",
            "RVN": "Rovaniemi",
            "SVG": "Stavanger",
            "TOS": "Tromso",
            "TRD": "Trondheim",
            # Netherlands, Belgium & Luxembourg
            "AMS": "Amsterdam",
            "BRU": "Brussels",
            "LUX": "Luxembourg",
            # Cyprus
            "LCA": "Larnaca",
            "PFO": "Paphos",
            # North Africa
            "AGA": "Agadir",
            "ALG": "Algiers",
            "CMN": "Casablanca",
            "ESU": "Essaouira",
            "FEZ": "Fez",
            "OUD": "Oujda",
            "RAK": "Marrakech",
            "TNG": "Tangier",
            "TUN": "Tunis",
            # Malta
            "MLA": "Malta",
            # North Africa baseline-listed
            "NBE": "Enfidha",
        },
    },
}


def get_destinations(airport: str) -> dict:
    entry = DESTINATIONS.get(airport, {})
    return entry.get("routes", {})


def get_airport_name(airport: str) -> str:
    entry = DESTINATIONS.get(airport, {})
    return entry.get("name", airport)
